name: wetland_example
description: "Wetland example"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  skeletonizer: ^1.4.2

  wetland:
    path: ../
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
